apiVersion: apps/v1
kind: Deployment
metadata:
  name: mymachine
  labels:
    app: mymachine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mymachine
  template:
    metadata:
      labels:
        app: mymachine
    spec:
      containers:
      - image: nginx
        name: mymachine
        ports:
        - containerPort: 22
---
  apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: mymachine-ssh
    name: mymachine-ssh
  spec:
      ports:
      - port: 22
        protocol: TCP
        targetPort: 22
      selector: 
        app: mymachine-ssh